brain.cpp
using json = nlohmann::json
auto timeLA
std::time_t timeT
bool placeFound
Referenced by main.
HashTable< std::string > nameBus("nameBus", 9)("nameBus", 9)
Referenced by findBusGo, findBusTaken.
HashTable< std::string > possible_buses("possiblebuses", 9)("possiblebuses", 9)
Referenced by findBusGo, findShortestBus.
ArrayList<std::string> possible_busnames
Referenced by findBusGo.
HashTable< std::string > possible_distances("possibledistances", 9)("possibledistances", 9)
Referenced by findBusGo, findShortestBus.
ArrayList<std::string> shortest_stops
Referenced by findBusGo.
HashTable< std::string > busGo_stops("busGostops", 9)("busGostops", 9)
Referenced by busGoStops, findBusGo.
HashTable< std::string > distances_dict("distancesdict", 9)("distancesdict", 9)
HashTable< std::string > shortestnames_stops("shortestnames_stops", 9)("shortestnames_stops", 9)
ArrayList<std::string> distances_list
HashTable< std::string > named_stops("named_stops", 9)("named_stops", 9)
Referenced by main.
std::string q1
Referenced by busGoStops, findBusGo, findBusSimilar, findbustoTake, main.
std::string q2
Referenced by findBusGo, findBusSimilar, findBusTaken, findbustoTake, main.
bool validatePlace(ArrayList< std::string > list, std::string target, int start, int end)
Referenced by main.
std::string Hash_binary_search(HashTable< std::string > &table, const std::string &target)
References HashTable< T >::getBuckets, HashTable< T >::getKeys, ArrayList< T >::getsize, HashTable< T >::search.
Referenced by busGoStops, findBusGo, findBusTaken, findShortestBus.
void findBusTaken()
References bus_stops_tables, Hash_binary_search, nameBus, q2.
void busGoStops()
References bus_stops_tables, busGo_stops, Hash_binary_search, q1.
float apiCalls(std::string point1, std::string point2, std::string point3)
Referenced by findBusGo, findBusSimilar.
void findbustoTake()
References ArrayList< T >::append, bus_stops_tables, ArrayList< T >::getsize, q1, q2.
void findBusSimilar()
References apiCalls, ArrayList< T >::append, bus_stops_tables, geo_places, ArrayList< T >::getsize, places, q1, q2.
Referenced by main.
void findBusGo()
References apiCalls, ArrayList< T >::append, busGo_stops, geo_places, Hash_binary_search, nameBus, places, possible_buses, possible_busnames, possible_distances, q1, q2, shortest_stops.
void findShortestBus()
References ArrayList< T >::append, Hash_binary_search, possible_buses, possible_distances.
int main()
References bus_names, bus_stops_tables, findBusSimilar, named_stops, placeFound, places, q1, q2, validatePlace.